import PDFDocument from "pdfkit";
import { StudentData } from "./pdfGenerator";
import fs from "fs";
import path from "path";

export const generateFeedbackFormPDF = (students: StudentData[], logoBuffer?: Buffer): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      // Landscape A4 setup
      const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 40 });
      const buffers: Buffer[] = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      const PRIMARY_COLOR = "#f97316";
      const SECONDARY_COLOR = "#334155";
      const BORDER_COLOR = "#cbd5e1";

      const maxPerPage = 10;
      let currentIndex = 0;

      while (currentIndex < students.length) {
        if (currentIndex > 0) {
          doc.addPage();
        }

        // Header section (Use Buffer if provided for speed)
        if (logoBuffer) {
          doc.image(logoBuffer, 40, 30, { width: 50 });
        } else {
          const logoPath = path.join(process.cwd(), "public", "gis_logo.png");
          if (fs.existsSync(logoPath)) {
            doc.image(logoPath, 40, 30, { width: 50 });
          }
        }
        
        doc.font("Helvetica-Bold").fontSize(20).fillColor(PRIMARY_COLOR);
        doc.text("GLOBAL INNOVATIVE SCHOOL", 110, 40);
        doc.fontSize(14).fillColor(SECONDARY_COLOR).text("Teacher Assessment & Feedback Form", 110, 65);
        doc.moveTo(40, 95).lineTo(doc.page.width - 40, 95).strokeColor(BORDER_COLOR).lineWidth(2).stroke();

        let y = 120;

        // Table Constants
        const startX = 40;
        const totalWidth = doc.page.width - 80; 
        
        const col1Width = totalWidth * 0.15; // 15% Name
        const col2Width = totalWidth * 0.70; // 70% Remark
        const col3Width = totalWidth * 0.15; // 15% Signature

        const col1X = startX;
        const col2X = startX + col1Width;
        const col3X = col2X + col2Width;

        // Draw Table Header
        doc.rect(startX, y, totalWidth, 25).fill("#f8fafc");
        doc.rect(startX, y, totalWidth, 25).strokeColor(BORDER_COLOR).lineWidth(1).stroke();

        doc.font("Helvetica-Bold").fontSize(10).fillColor(PRIMARY_COLOR);
        doc.text("STUDENT NAME", col1X + 10, y + 8);
        doc.text("REMARK", col2X + 10, y + 8);
        doc.text("SIGNATURE", col3X + 10, y + 8);

        // Vertical lines for header
        doc.moveTo(col2X, y).lineTo(col2X, y + 25).stroke();
        doc.moveTo(col3X, y).lineTo(col3X, y + 25).stroke();

        y += 25;

        // Draw Table Body (up to 10 rows)
        const rowHeight = 36;
        const endIndex = Math.min(currentIndex + maxPerPage, students.length);
        
        for (let i = currentIndex; i < endIndex; i++) {
          const st = students[i];
          
          doc.rect(startX, y, totalWidth, rowHeight).strokeColor(BORDER_COLOR).stroke();
          
          doc.font("Helvetica-Bold").fontSize(10).fillColor(SECONDARY_COLOR);
          doc.text(st.name.toUpperCase(), col1X + 10, y + 12, { width: col1Width - 20, height: 20, ellipsis: true });
          
          doc.font("Helvetica").fontSize(9).fillColor("#475569");
          // Remark left completely blank for manual entry 
          doc.text("", col2X + 10, y + 8, { width: col2Width - 20, height: 24 });
          
          // Signature stays blank
          
          // Vertical lines for row
          doc.moveTo(col2X, y).lineTo(col2X, y + rowHeight).stroke();
          doc.moveTo(col3X, y).lineTo(col3X, y + rowHeight).stroke();
          
          y += rowHeight;
        }

        currentIndex = endIndex;
        
        // Footer Page Num
        doc.font("Helvetica").fontSize(8).fillColor(BORDER_COLOR);
        doc.text(`Generated by GIS Portal - Page ${Math.ceil(currentIndex/maxPerPage)}`, 40, doc.page.height - 30, { align: 'center' });
      }

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
};
