import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export interface StudentData {
  name: string;
  fatherName: string;
  motherName: string;
  className: string;
  dob: string;
  qualities: string;
  workingDays: number;
  attendedDays: number;
  subjects: { name: string; marks: SubjectMarks }[];
  remarks?: string; // Generated by LLM
}

export interface SubjectMarks {
  periodicRaw: number; // Out of 20
  enrichment: number;  // Out of 10
  term2: number;       // Out of 80
}

const getGrade = (percentage: number): string => {
  if (percentage >= 91) return "A1";
  if (percentage >= 81) return "A2";
  if (percentage >= 71) return "B1";
  if (percentage >= 61) return "B2";
  if (percentage >= 51) return "C1";
  if (percentage >= 41) return "C2";
  if (percentage >= 33) return "D";
  return "E";
};

const toTitleCase = (str: string): string => {
  return (str || "")
    .toLowerCase()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

export const generateReportCardPDF = (data: StudentData, logoBuffer?: Buffer): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 0 });
      const buffers: Buffer[] = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      // ─── EXACT STYLING FROM IMAGE 1 ────────────────────────────────
      const BLUE_BRAND  = "#1f497d"; // Professional Deep Blue used in Image 1
      const BLUE_HEADER = "#e3f2fd"; // Light Baby Blue banner
      const GREEN_ATT   = "#2e7d32"; // Dark Green
      const BLACK       = "#000000";
      const WHITE       = "#ffffff";
      const MARGIN_X    = 45;
      const PAGE_W      = doc.page.width;

      // ─── HEADER SECTION ───────────────────────────────────────────
      doc.rect(0, 0, PAGE_W, 100).fill(BLUE_HEADER);

      // Logo - Clamped for consistency
      if (logoBuffer) {
        try { doc.image(logoBuffer, MARGIN_X, 15, { width: 75 }); } catch(_) {}
      } else {
        const logoPath = path.join(process.cwd(), "public", "gis_logo.png");
        if (fs.existsSync(logoPath)) {
          try { doc.image(logoPath, MARGIN_X, 15, { width: 75 }); } catch(_) {}
        }
      }

      // School Name
      doc.font("Helvetica-Bold").fontSize(26).fillColor(BLUE_BRAND);
      doc.text("GLOBAL INNOVATIVE SCHOOL", 140, 38);

      // Report Card Title (Centered)
      doc.font("Helvetica-Bold").fontSize(28).fillColor(BLUE_BRAND); // Slightly larger title
      doc.text("REPORT CARD", 0, 115, { align: "center", width: PAGE_W });

      // ─── STUDENT DETAILS (Casing & Alignment Fix) ──────────────────
      let y = 145;
      const colL = MARGIN_X;
      const colR = 300;
      const underlineW = 180;
      const VAL_OFFSET_Y = 1.8; // Fix entries going above the line

      const drawDetail = (label: string, value: string, x: number, ly: number) => {
        doc.font("Helvetica-Bold").fontSize(11).fillColor(BLUE_BRAND).text(label, x, ly);
        const labelW = doc.widthOfString(label);
        // Corrected Casing and Alignment (Shifted down by VAL_OFFSET_Y)
        doc.font("Helvetica").fontSize(11).fillColor(BLACK).text(toTitleCase(value), x + labelW + 8, ly + VAL_OFFSET_Y);
        // Underline in BRAND BLUE
        doc.moveTo(x + labelW + 4, ly + 14).lineTo(x + labelW + underlineW, ly + 14)
          .strokeColor(BLUE_BRAND).lineWidth(0.8).stroke();
      };

      drawDetail("NAME:", data.name, colL, y);
      drawDetail("Mother's Name:", data.motherName, colR, y);
      y += 28;
      drawDetail("CLASS:", data.className, colL, y);
      drawDetail("Father's Name:", data.fatherName, colR, y);
      y += 28;
      drawDetail("DOB:", data.dob, colL, y);

      y += 40;

      // ─── SUBJECT TABLE ───────────────────────────────────────────
      const tableX = MARGIN_X;
      const tableW = PAGE_W - MARGIN_X * 2;
      const colW   = [110, 110, 110, 100, 75]; 
      const xPos   = [0, 110, 220, 330, 430].map(v => v + tableX);

      const headH = 34;
      doc.rect(tableX, y, tableW, headH).fill(BLUE_HEADER);
      doc.rect(tableX, y, tableW, headH).strokeColor(BLUE_BRAND).stroke();
      
      for (let i = 1; i < xPos.length; i++) {
        doc.moveTo(xPos[i], y).lineTo(xPos[i], y + headH).stroke();
      }

      doc.font("Helvetica-Bold").fontSize(9).fillColor(BLUE_BRAND);
      doc.text("Subject", tableX + 5, y + 12);
      doc.text("Periodic Test - 2\n(Out of 10)", xPos[1] + 5, y + 6);
      doc.text("Subject Enrichment\n(Out of 10)", xPos[2] + 5, y + 6);
      doc.text("Term - 2 Examination\n(Out of 80)", xPos[3] + 5, y + 6);
      doc.text("Overall Marks\n(Out of 100)", xPos[4] + 5, y + 6);

      y += headH;
      let totalMarksAccumulated = 0;

      data.subjects.forEach(subject => {
        // SCALING LOGIC: Scale out of 20 to 10
        const rawP = Number(subject.marks.periodicRaw) || 0;
        const p = Math.round(rawP / 2); // Scales down to 10 and rounds (e.g., 15->8)
        
        const e = Number(subject.marks.enrichment) || 0;
        const t = Number(subject.marks.term2) || 0;
        const sum = p + e + t;
        totalMarksAccumulated += sum;

        doc.rect(tableX, y, tableW, 26).strokeColor(BLUE_BRAND).stroke();
        for (let i = 1; i < xPos.length; i++) {
          doc.moveTo(xPos[i], y).lineTo(xPos[i], y + 26).stroke();
        }

        doc.font("Helvetica-Bold").fontSize(10.5).fillColor(BLACK).text(subject.name, tableX + 5, y + 7.5);
        doc.font("Helvetica").fontSize(11).text(p.toString(), xPos[1] + 5, y + 7.5);
        doc.text(e.toString(), xPos[2] + 5, y + 7.5);
        doc.text(t.toString(), xPos[3] + 5, y + 7.5);
        doc.text(sum.toString(), xPos[4] + 5, y + 7.5);
        y += 26;
      });

      y += 24;

      // ─── STATS & ATTENDANCE (Alignment Fix) ───────────────────────
      const totalPossible = data.subjects.length * 100;
      const percentage    = totalPossible > 0 ? (totalMarksAccumulated / totalPossible) * 100 : 0;
      const grade         = getGrade(percentage);

      const drawStat = (label: string, value: string, sy: number) => {
        doc.font("Helvetica-Bold").fontSize(11).fillColor(BLUE_BRAND).text(label, MARGIN_X, sy);
        doc.font("Helvetica").fillColor(BLACK).text(value, MARGIN_X + 130, sy + VAL_OFFSET_Y);
        doc.moveTo(MARGIN_X + 125, sy + 14).lineTo(MARGIN_X + 260, sy + 14).strokeColor(BLUE_BRAND).stroke();
      };

      drawStat("Overall Marks:", `${totalMarksAccumulated} / ${totalPossible}`, y);
      drawStat("Overall Percentage:", `${percentage.toFixed(2)}%`, y + 26);
      drawStat("Overall Grade:", grade, y + 52);

      const attX = 330;
      const attW = PAGE_W - MARGIN_X - attX;
      doc.font("Helvetica-Bold").fontSize(11).fillColor(BLUE_BRAND);
      doc.text("Attendance", attX, y, { width: attW, align: "center" });
      y += 18;

      const drawAtt = (label: string, val: string, ry: number, isLast = false) => {
        doc.rect(attX, ry, attW, 24).strokeColor(BLUE_BRAND).stroke();
        doc.moveTo(attX + 140, ry).lineTo(attX + 140, ry + 24).stroke();
        doc.font("Helvetica-Bold").fontSize(9).fillColor(GREEN_ATT).text(label, attX + 5, ry + 7);
        doc.font("Helvetica-Bold").fontSize(10).fillColor(isLast ? BLUE_BRAND : BLACK).text(val, attX + 148, ry + 7 + VAL_OFFSET_Y);
      };

      drawAtt("Total Working Days", data.workingDays.toString(), y);
      drawAtt("Number of Days Attended", data.attendedDays.toString(), y + 24);
      const attPer = data.workingDays > 0 ? ((data.attendedDays / data.workingDays) * 100).toFixed(2) : "0.00";
      drawAtt("Attendance Percentage", `${attPer}%`, y + 48, true);

      y += 100;

      // ─── BOTTOM SECTION ───────────────────────────────────────────
      doc.rect(0, y - 10, PAGE_W, 300).fill(BLUE_HEADER);

      const boxH = 100;
      doc.rect(MARGIN_X, y, tableW, boxH).fill(WHITE).strokeColor(BLUE_HEADER).stroke();
      doc.font("Helvetica-Bold").fontSize(10.5).fillColor(BLUE_BRAND).text("Teacher's Remark:", MARGIN_X + 10, y + 10);
      if (data.remarks) {
        doc.font("Helvetica").fontSize(10).fillColor(BLACK);
        doc.text(data.remarks, MARGIN_X + 10, y + 28, { width: 485, lineGap: 5 });
      }

      y += boxH + 60;

      // Lines
      const lineL = 145;
      doc.strokeColor(BLUE_BRAND).lineWidth(1.2);
      doc.moveTo(MARGIN_X, y).lineTo(MARGIN_X + lineL, y).stroke();
      doc.moveTo(PAGE_W - MARGIN_X - lineL, y).lineTo(PAGE_W - MARGIN_X, y).stroke();

      doc.font("Helvetica").fontSize(10).fillColor(BLACK);
      doc.text("Class Teacher", MARGIN_X, y + 10, { width: lineL, align: "center" });
      doc.text("School Stamp", 0, y + 10, { width: PAGE_W, align: "center" });
      doc.text("Principal", PAGE_W - MARGIN_X - lineL, y + 10, { width: lineL, align: "center" });

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
};

