import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export interface StudentData {
  name: string;
  fatherName: string;
  motherName: string;
  className: string;
  dob: string;
  qualities: string;
  workingDays: number;
  attendedDays: number;
  subjects: { name: string; marks: SubjectMarks }[];
  remarks?: string; // Generated by LLM
}

export interface SubjectMarks {
  periodicRaw: number; // Out of 20
  enrichment: number;  // Out of 10
  term2: number;       // Out of 80
}

const getGrade = (percentage: number): string => {
  if (percentage >= 91) return "A1";
  if (percentage >= 81) return "A2";
  if (percentage >= 71) return "B1";
  if (percentage >= 61) return "B2";
  if (percentage >= 51) return "C1";
  if (percentage >= 41) return "C2";
  if (percentage >= 33) return "D";
  return "E";
};

export const generateReportCardPDF = (data: StudentData, logoBuffer?: Buffer): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 40 });
      const buffers: Buffer[] = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      const PRIMARY_COLOR = "#f97316";
      const SECONDARY_COLOR = "#000000";
      // Exact match for the background of the supplied logo image
      const BG_LIGHT_BLUE = "#fff7ed";

      // Top Background Banner
      doc.rect(0, 0, doc.page.width, 100).fill(BG_LIGHT_BLUE);

      // Logo (Use Buffer if provided for speed, otherwise read from disk)
      if (logoBuffer) {
        doc.image(logoBuffer, 50, 20, { width: 70 });
      } else {
        const logoPath = path.join(process.cwd(), "public", "gis_logo.png");
        if (fs.existsSync(logoPath)) {
          try {
            doc.image(logoPath, 50, 20, { width: 70 });
          } catch (imgError) {
            console.error("Logo image error:", imgError);
            doc.rect(50, 20, 70, 70).strokeColor(PRIMARY_COLOR).lineWidth(2).stroke();
            doc.font("Helvetica-Bold").fontSize(8).fillColor(PRIMARY_COLOR).text("GIS LOGO", 50, 50, { width: 70, align: "center" });
          }
        } else {
          doc.rect(50, 20, 70, 70).strokeColor(PRIMARY_COLOR).lineWidth(2).stroke();
          doc.font("Helvetica-Bold").fontSize(8).fillColor(PRIMARY_COLOR).text("GIS LOGO", 50, 50, { width: 70, align: "center" });
        }
      }

      // School Name Title
      doc.font("Helvetica-Bold").fontSize(24).fillColor(PRIMARY_COLOR);
      doc.text("GLOBAL INNOVATIVE SCHOOL", 160, 40);

      // Report Card Title
      doc.moveDown(2);
      doc.font("Helvetica-Bold").fontSize(18).fillColor(PRIMARY_COLOR);
      doc.text("REPORT CARD", 0, doc.y, { align: "center", width: doc.page.width });

      // Student Details Section
      doc.moveDown(1);
      doc.font("Helvetica-Bold").fontSize(10).fillColor(PRIMARY_COLOR);
      const startX = 50;
      const rightX = 300;
      let y = doc.y;

      const drawDetailLine = (label: string, value: string, x: number, lineY: number) => {
        doc.font("Helvetica-Bold").fillColor(PRIMARY_COLOR).text(label, x, lineY);
        doc.font("Helvetica").fillColor(SECONDARY_COLOR).text((value || "").toUpperCase(), x + 90, lineY);
        doc.moveTo(x + 85, lineY + 12).lineTo(x + 240, lineY + 12).strokeColor("#cccccc").lineWidth(1).stroke();
      };

      drawDetailLine("NAME:", data.name, startX, y);
      drawDetailLine("Mother's Name:", data.motherName, rightX, y);
      y += 25;
      drawDetailLine("CLASS:", data.className, startX, y);
      drawDetailLine("Father's Name:", data.fatherName, rightX, y);
      y += 25;
      drawDetailLine("DOB:", data.dob, startX, y);

      y += 40;

      // Table Header Background
      doc.rect(startX, y, 500, 30).fill(BG_LIGHT_BLUE);
      doc.rect(startX, y, 500, 30).strokeColor(PRIMARY_COLOR).stroke();

      // Table Headers
      const colX1 = startX + 100;
      const colX2 = colX1 + 100;
      const colX3 = colX2 + 100;
      const colX4 = colX3 + 100;

      doc.font("Helvetica-Bold").fontSize(9).fillColor(PRIMARY_COLOR);
      doc.text("Subject", startX + 5, y + 10);
      doc.text("Periodic Test - 2\n(Out of 10)", colX1 + 5, y + 5);
      doc.text("Subject Enrichment\n(Out of 10)", colX2 + 5, y + 5);
      doc.text("Term - 2 Examination\n(Out of 80)", colX3 + 5, y + 5);
      doc.text("Overall Marks\n(Out of 100)", colX4 + 5, y + 5);

      y += 30;

      const subjectRowHeight = 25;
      let totalGrand = 0;
      let subjectCount = 0;

      const drawSubjectRow = (label: string, marks: SubjectMarks) => {
        const p10 = Math.round((marks.periodicRaw / 20) * 10); // scale to 10 and round
        const overall = p10 + marks.enrichment + marks.term2;
        totalGrand += overall;
        subjectCount++;

        doc.rect(startX, y, 500, subjectRowHeight).strokeColor(PRIMARY_COLOR).stroke();
        doc.font("Helvetica-Bold").fontSize(10).fillColor(SECONDARY_COLOR).text(label, startX + 5, y + 7);
        doc.font("Helvetica").fontSize(12).text(p10.toString(), colX1 + 5, y + 7);
        doc.text(marks.enrichment.toString(), colX2 + 5, y + 7);
        doc.text(marks.term2.toString(), colX3 + 5, y + 7);
        doc.text(overall.toString(), colX4 + 5, y + 7);
        
        y += subjectRowHeight;
      };

      data.subjects.forEach(subject => {
        drawSubjectRow(subject.name, subject.marks);
      });

      // Draw Vertical Table Lines
      const tableBottom = y;
      const tableTop = y - (subjectRowHeight * data.subjects.length) - 30;
      doc.moveTo(colX1, tableTop).lineTo(colX1, tableBottom).stroke();
      doc.moveTo(colX2, tableTop).lineTo(colX2, tableBottom).stroke();
      doc.moveTo(colX3, tableTop).lineTo(colX3, tableBottom).stroke();
      doc.moveTo(colX4, tableTop).lineTo(colX4, tableBottom).stroke();
      doc.moveTo(startX + 500, tableTop).lineTo(startX + 500, tableBottom).stroke();

      y += 30;

      // Totals
      const totalPossible = data.subjects.length * 100;
      const percentage = (totalGrand / totalPossible) * 100;
      const grade = getGrade(percentage);

      doc.font("Helvetica-Bold").fontSize(10).fillColor(PRIMARY_COLOR);
      doc.text(`Overall Marks:`, startX, y);
      doc.font("Helvetica").fillColor(SECONDARY_COLOR).text(`  ${totalGrand} / ${totalPossible}`, startX + 80, y);
      doc.moveTo(startX + 80, y + 12).lineTo(startX + 200, y + 12).strokeColor(PRIMARY_COLOR).stroke();
      
      y += 25;
      doc.font("Helvetica-Bold").fillColor(PRIMARY_COLOR).text(`Overall Percentage:`, startX, y);
      doc.font("Helvetica").fillColor(SECONDARY_COLOR).text(`  ${percentage.toFixed(2)}%`, startX + 110, y);
      doc.moveTo(startX + 110, y + 12).lineTo(startX + 200, y + 12).stroke();
      
      y += 25;
      doc.font("Helvetica-Bold").fillColor(PRIMARY_COLOR).text(`Overall Grade:`, startX, y);
      doc.font("Helvetica").fillColor(SECONDARY_COLOR).text(`  ${grade}`, startX + 80, y);
      doc.moveTo(startX + 80, y + 12).lineTo(startX + 200, y + 12).stroke();

      // Attendance Table
      const attY = y - 50;
      doc.font("Helvetica-Bold").fillColor(PRIMARY_COLOR).text("Attendance", 400, attY);
      doc.rect(330, attY + 15, 220, 20).strokeColor(PRIMARY_COLOR).stroke();
      doc.font("Helvetica").fontSize(9).fillColor("#2fa331").text("Total Working Days", 335, attY + 20);
      doc.fillColor(SECONDARY_COLOR).text(data.workingDays.toString(), 465, attY + 20);
      
      doc.rect(330, attY + 35, 220, 20).stroke();
      doc.font("Helvetica").fillColor("#2fa331").text("Number of Days Attended", 335, attY + 40);
      doc.fillColor(SECONDARY_COLOR).text(data.attendedDays.toString(), 465, attY + 40);

      // Third row: Attendance Percentage
      const attendancePercent = data.workingDays > 0 
        ? ((data.attendedDays / data.workingDays) * 100).toFixed(2) 
        : "0.00";
      doc.rect(330, attY + 55, 220, 20).stroke();
      doc.font("Helvetica-Bold").fillColor("#2fa331").text("Attendance Percentage", 335, attY + 60);
      doc.fillColor(PRIMARY_COLOR).text(`${attendancePercent}%`, 465, attY + 60);

      // vertical line inside attendance spanning 3 rows (20px each = 60px height starting offset 15, ending at 75)
      doc.moveTo(460, attY + 15).lineTo(460, attY + 75).stroke();

      y += 60;

      // Remarks Box
      doc.rect(0, y, doc.page.width, 250).fill(BG_LIGHT_BLUE);
      doc.rect(startX, y + 20, 500, 100).fill("#ffffff");
      
      doc.font("Helvetica-Bold").fontSize(10).fillColor(PRIMARY_COLOR);
      doc.text("Teacher's Remark:", startX + 10, y + 30);
      
      if (data.remarks) {
        doc.font("Helvetica").fillColor(SECONDARY_COLOR);
        doc.text(data.remarks, startX + 10, y + 50, { width: 480, lineGap: 4 });
      }

      // Signatures
      y += 180;
      doc.moveTo(startX, y).lineTo(startX + 120, y).strokeColor(PRIMARY_COLOR).stroke();
      doc.text("Class Teacher", startX + 20, y + 10);

      doc.text("School Stamp", 260, y + 10);

      const endX = startX + 500;
      doc.moveTo(endX - 120, y).lineTo(endX, y).stroke();
      doc.text("Principal", endX - 80, y + 10);

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
};
